In [1]:
import torch
print(torch.cuda.is_available())

/Users/anna.felix/Documents/post_projects/Python/Analysis/.venv/lib/python3.14/site-packages/torch/_subclasses/functional_tensor.py:279: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


False


In [6]:
x = torch.ones(2,5, dtype=torch.double)
print(x)
print(x.size())
print(x.type())

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
torch.Size([2, 5])
torch.DoubleTensor


In [11]:
x = torch.rand(2,5)
y = torch.ones(2,5)
print(x+y)
print(x)
print(x[1,1])

tensor([[1.2199, 1.1989, 1.7198, 1.3331, 1.0263],
        [1.6483, 1.8047, 1.0084, 1.2558, 1.0972]])
tensor([[0.2199, 0.1989, 0.7198, 0.3331, 0.0263],
        [0.6483, 0.8047, 0.0084, 0.2558, 0.0972]])
tensor(0.8047)


In [16]:
x = torch.empty(5)
print(x)

tensor([0., 0., 0., 0., 0.])


In [19]:
# ----- While loop tutorial ----

limit = input("Enter the range?")
limit_ref = int(limit)
print("Start printing"+ str(limit_ref))
n = 0
while n < limit_ref:
    n = n + 1
    print(n)


print("End printing"+ str(limit_ref))




Start printing6
0
1
2
3
4
5
End printing6


In [23]:
# While example 2

name = input("Enter your name")
exp_name = "Ann"

while not name == exp_name:
    name = input("Enter your name")

print("End printing")


End printing


In [ ]:
# While example 2

name = input("Enter your name")
exp_name = "Ann"

while not name == exp_name:
    name = input("Enter your name")

print("End printing")


In [39]:
def get_ref(*args, **kwargs):
    print("Enter args:", args)

    for n, arg in enumerate(args, start=1):
        print(f"Arg {n}: {arg}")

    print("Enter kwargs:", kwargs)

    for key, value in kwargs.items():
        print(f"Key {key}: Value {value}")


get_ref(1, 2, "Ref arg", age = 2, name = "Ann")

Enter args: (1, 2, 'Ref arg')
Arg 1: 1
Arg 2: 2
Arg 3: Ref arg
Enter kwargs: {'age': 2, 'name': 'Ann'}
Key age: Value 2
Key name: Value Ann


In [41]:
def ref_func(*args, **kwargs):
    print("Enter args:", args)
    for n, args in enumerate(args, start=1):
        print(f"Arg {n}: {args}")
    for key, value in kwargs.items():
        print(f"Key {key}: Value {value}")

ref_func("Ref arg", 3,44,55,66, age = 2, name = "Ann")


Enter args: ('Ref arg', 3, 44, 55, 66)
Arg 1: Ref arg
Arg 2: 3
Arg 3: 44
Arg 4: 55
Arg 5: 66
Key age: Value 2
Key name: Value Ann


In [44]:
def f1():
    print("Enter f1: to ask Age")
    age = input("Enter age")
    def f2():
        if int(age) < 10:
            f1()
        else:
            print("normal!")
    f2()

f1()





Enter f1: to ask Age
Enter f1: to ask Age
Enter f1: to ask Age
Enter f1: to ask Age
normal!


In [48]:
def magic_age():
    age = input("Enter your age:")
    age_magic = int(age)
    if int(age) < 10:
        print("Child!")
        age_magic = 5
    elif int(age) < 20:
        print("Teenage!")
        age_magic = 10
    elif int(age) < 40:
        print("Adult!")
        age_magic = 30
    else:
        print("Awsome!")
        age_magic = 50
    return age_magic

if magic_age() == 50:
    print("Welcome!")




Awsome!
Welcome!


In [5]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

car1 = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.items()
y = car1.keys()

print(x) #before the change
print(y)
car["brand"] = "Ford"

car["color"] = "red"
car["designer"] = "DEV1"
car["year"] = 30

print(x) #after the change
print(y)

dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964)])
dict_keys(['brand', 'model', 'year'])
dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 30), ('color', 'red'), ('designer', 'DEV1')])
dict_keys(['brand', 'model', 'year'])
