In [2]:
import numpy as np
from sympy.physics.units import years

test = np.genfromtxt(
    "file/exp1.csv",
    delimiter=",",
    dtype=str,
    skip_header=True,
)

print(test)



[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]


In [3]:
countries = test[:, 2]
print(countries)
years  = test[:, 0]
print(years)
data = test[2, :]
print("data")
print(data)

['Viet Nam' 'Uruguay' "Cte d'Ivoire" ... 'Switzerland' 'Papua New Guinea'
 'Swaziland']
['1986' '1986' '1985' ... '1986' '1987' '1986']
data
['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']


In [4]:
exam1 = test[:, 0:2]
print(exam1)


[['1986' 'Western Pacific']
 ['1986' 'Americas']
 ['1985' 'Africa']
 ...
 ['1986' 'Europe']
 ['1987' 'Western Pacific']
 ['1986' 'Africa']]


In [5]:
exam2 = test[0:10, 0]
print(exam2)

['1986' '1986' '1985' '1986' '1987' '1987' '1987' '1985' '1986' '1984']


In [6]:
exam3 = test[0:10, 0:]
print(exam3)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ['1986' 'Americas' 'Colombia' 'Beer' '4.27']
 ['1987' 'Americas' 'Saint Kitts and Nevis' 'Beer' '1.98']
 ['1987' 'Americas' 'Guatemala' 'Other' '0']
 ['1987' 'Africa' 'Mauritius' 'Wine' '0.13']
 ['1985' 'Africa' 'Angola' 'Spirits' '0.39']
 ['1986' 'Americas' 'Antigua and Barbuda' 'Spirits' '1.55']
 ['1984' 'Africa' 'Nigeria' 'Other' '6.1']]


In [11]:
exam4 = test[0:20, 0:2]
print(exam4)

[['1986' 'Western Pacific']
 ['1986' 'Americas']
 ['1985' 'Africa']
 ['1986' 'Americas']
 ['1987' 'Americas']
 ['1987' 'Americas']
 ['1987' 'Africa']
 ['1985' 'Africa']
 ['1986' 'Americas']
 ['1984' 'Africa']
 ['1987' 'Africa']
 ['1989' 'Americas']
 ['1985' 'Western Pacific']
 ['1984' 'Eastern Mediterranean']
 ['1985' 'Western Pacific']
 ['1987' 'Africa']
 ['1984' 'Americas']
 ['1989' 'Africa']
 ['1984' 'Europe']
 ['1984' 'Africa']]


In [42]:
numbers = np.array([1,2])
print(numbers)
print(numbers.dtype)
print(numbers.size)
print(numbers.T[0])
print(numbers.T[1])
print(numbers.T)

[1 2]
int64
2
1
2
[1 2]


In [43]:
test_1986 = test[1]
print(test_1986)

['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']


In [33]:
print(test.dtype)

<U29


In [40]:
two_d = np.array([[1,2],[3,4]])
print(two_d)
print(two_d.dtype)
print(two_d *2)
print(two_d ** 2)

[[1 2]
 [3 4]]
int64
[[2 4]
 [6 8]]
[[ 1  4]
 [ 9 16]]


In [51]:
vector  = np.array([1,2,3,4,5])
print(vector)
print(vector.dtype)
print(vector[:4])
print(vector[1:4])
print(vector[3:4])
print(vector[1:4] )    # index 1 to 3
print(vector[:3])     # start to index 2
print(vector[2:] )     # index 2 to end
print(vector[::2] )    # every 2nd element




[1 2 3 4 5]
int64
[1 2 3 4]
[2 3 4]
[4]
[2 3 4]
[1 2 3]
[3 4 5]
[1 3 5]


In [57]:
two_decimal = np.array([[1,2,3,4,5],[11,12,13,14,15]])
print(two_decimal)
print(two_decimal[:, 1:3])

[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[[ 2  3]
 [12 13]]
